### ISSUE TITLE
Colour compatibility 

### ISSUE THREAD

**Issue by infojamjames** [andymarsden/pbi-templates#9]
![image](https://github.com/andymarsden/pbi-templates/assets/87974094/67a044ae-3d33-4e7b-809c-cb79a7cf0a23)

**Comment by infojamjames** [comment]
If we change the master colour, we will still have issues with other fonts.
![image](https://github.com/andymarsden/pbi-templates/assets/87974094/9f9d6320-e005-4ec6-9c48-08888307ced9)
![image](https://github.com/andymarsden/pbi-templates/assets/87974094/7fc3455a-dd7d-4618-a4b9-43513539d4f0)

**Comment by sylwiasajdakLCC** [comment]
Soooo that's a whole can of worms. I think this sort of goes back to an issue mentioned during the call with Ashleigh and Laura last week where the intention is to have the ONS accessible colours (found here: https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-colours-in-charts/#section-5 ) used in the template. 

So I guess step one is to change the colours to the ONS ones in the first place. From there we can consider the text contrast issue.

It may be that it's not something that can be fixed in the template and instead will need to be considered in the guidance. For example linking to this grid which details the WCAG compliance against different text colours: https://contrast-grid.eightshapes.com/?version=1.1.0&background-colors=%2312436D%2C%20Dark%20blue%0D%0A%2328A197%2C%20Turquoise%0D%0A%23801650%2C%20Dark%20pink%0D%0A%23F46A25%2C%20Orange%0D%0A%233D3D3D%2C%20Dark%20grey%0D%0A%23A285D1%2C%20Light%20purple&foreground-colors=%23ffffff%2C%20White%0D%0A%23000000%2C%20Black&es-color-form__tile-size=regular&es-color-form__show-contrast=aaa&es-color-form__show-contrast=aa&es-color-form__show-contrast=aa18&es-color-form__show-contrast=dnp

**Comment by infojamjames** [comment]
I think its quite a major change, I'll pass it over to Laura, Andy and Stewart to discuss. As we could be on this for a while and we need to get the template sorted by the end of the day.

**Comment by infojamjames** [comment]
However, we could train the user to turn on high contrast modes 
![image](https://github.com/andymarsden/pbi-templates/assets/87974094/bf63d729-7735-4d8b-94e5-bb90f97134b5)
![image](https://github.com/andymarsden/pbi-templates/assets/87974094/3c7eb7e0-61f3-4e89-bd9d-ad788e5126c7)
